name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v4
      
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Verify project structure
      run: |
        echo "Checking project structure..."
        ls -la app/src/main/java/com/chevz/melapor/
        echo "Checking manifest package..."
        grep "package=" app/src/main/AndroidManifest.xml
        
    - name: Clean project
      run: ./gradlew clean
      
    - name: Generate R class
      run: ./gradlew generateDebugResources
      
    - name: Check R class generation
      run: |
        echo "Checking if R.java is generated..."
        find . -name "R.java" -type f || echo "R.java not found"
      
    - name: Build APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk
